### ISSUE TITLE
indent using spaces or tab?

### ISSUE THREAD

**Issue by dongyuwei** [tsloughter/erl_tidy#2]
My current Erlang source code using spaces as indentation, after the reformation of `erl_tidy`, it has both spaces and tab indentation, which is not acceptable for me. Is there some config options for indentation?

**Comment by fstiffo** [comment]
I have the same problem. elr_tidy needs more formatting options, it makes a good job in fixing  programming style but it is not a good code prettify tool.

**Comment by vladimir-vg** [comment]
Currently erl_tidy relies on http://erlang.org/doc/man/erl_prettypr.html formatter with default printing opts.
Actually it's possible to provide `{hook, _}` options to erl_prettypr, with special function that will use http://erlang.org/doc/man/prettypr.html module to format code using spaces.

But it will require some work.

**Comment by vladimir-vg** [comment]
Actually current implementation turns following literal into single string literal in AST
```
X = [
      "SELECT instance_id, context\n"
      "FROM `", DBName, "`.events\n"
      "WHERE ", clickhouse:id_in_values_sql(<<"instance_id">>, Ids), "\n"
      "\tAND context != ''\n"
      "GROUP BY instance_id, context\n"
      "ORDER BY min(at_s) DESC\n"
      "FORMAT TabSeparatedWithNamesAndTypes\n"
      ]
```
So it does mix it all together, into one string literal.
Looks like just hooking into erl_prettypr is not enough. Need more nuanced parser.

**Comment by dongyuwei** [comment]
erl_prettypr is not easy to hack. What about provide a post hook and replace all tab with space?

**Comment by vladimir-vg** [comment]
Might work for tabs, but not right way to go in long run.

**Comment by tsloughter** [comment]
This should definitely use only spaces and no tabs. OTP itself has moved to only spaces recently.
